
// src/agent.js
import { Actor, HttpAgent } from '@dfinity/agent';
import { idlFactory } from './declaration/project1_backend.did.js'; // This file should be generated by DFX

const canisterId = 'your-canister-id'; // Replace with your canister ID

const agent = new HttpAgent();
agent.fetchRootKey(); // Only needed if you are developing locally

export const trustSystem = Actor.createActor(idlFactory, {
  agent,
  canisterId,
});
